/*
 *
 *    GLSL ES header
 *
 */

#ifdef __cplusplus
extern "C" {
#endif

#include <windows.h>

#ifdef LIBGLESV2_EXPORTS
#	define LIBGLSL_API __declspec(dllexport)
#else
#	define LIBGLSL_API __declspec(dllimport)
#endif

#include <GL/gl.h>

typedef GLclampf	GLfloat;
typedef int         GLfixed;


#include <GL/glext.h>
#include <GL/wglext.h>

#ifndef GL_APIENTRY
#define GL_APIENTRY
#endif
#ifndef GL_APIENTRYP
#   define GL_APIENTRYP GL_APIENTRY*
#endif


/* OpenGL ES core versions */
#define GL_ES_VERSION_2_0                 1

#define GL_RGB565                         0x8D62

#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS         0x8CD9

#undef GL_COVERAGE_SAMPLES_NV

#include <GLES2/gl2ext.h>

/* WGL_ARB_extensions_string */
extern LIBGLSL_API PFNWGLGETEXTENSIONSSTRINGARBPROC wglGetExtensionsStringARB;

/* WGL_ARB_create_context */
extern LIBGLSL_API PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;

/* WGL_ARB_pixel_format */
extern LIBGLSL_API PFNWGLGETPIXELFORMATATTRIBIVARBPROC wglGetPixelFormatAttribivARB;
extern LIBGLSL_API PFNWGLGETPIXELFORMATATTRIBFVARBPROC wglGetPixelFormatAttribfvARB;
extern LIBGLSL_API PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB;

/* WGL_ARB_make_current_read */
extern LIBGLSL_API PFNWGLMAKECONTEXTCURRENTARBPROC wglMakeContextCurrentARB;
extern LIBGLSL_API PFNWGLGETCURRENTREADDCARBPROC wglGetCurrentReadDCARB;

/* WGL_ARB_pbuffer */
extern LIBGLSL_API PFNWGLCREATEPBUFFERARBPROC wglCreatePbufferARB;
extern LIBGLSL_API PFNWGLGETPBUFFERDCARBPROC wglGetPbufferDCARB;
extern LIBGLSL_API PFNWGLRELEASEPBUFFERDCARBPROC wglReleasePbufferDCARB;
extern LIBGLSL_API PFNWGLDESTROYPBUFFERARBPROC wglDestroyPbufferARB;
extern LIBGLSL_API PFNWGLQUERYPBUFFERARBPROC wglQueryPbufferARB;

/* WGL_EXT_swap_control */
extern LIBGLSL_API PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT;
extern LIBGLSL_API PFNWGLGETSWAPINTERVALEXTPROC wglGetSwapIntervalEXT;

/* EXT_framebuffer_object */
extern LIBGLSL_API PFNGLISRENDERBUFFEREXTPROC				glIsRenderbufferEXT;
extern LIBGLSL_API PFNGLBINDRENDERBUFFEREXTPROC				glBindRenderbufferEXT;
extern LIBGLSL_API PFNGLDELETERENDERBUFFERSEXTPROC			glDeleteRenderbuffersEXT;
extern LIBGLSL_API PFNGLGENRENDERBUFFERSEXTPROC				glGenRenderbuffersEXT;
extern LIBGLSL_API PFNGLRENDERBUFFERSTORAGEEXTPROC			glRenderbufferStorageEXT;
extern LIBGLSL_API PFNGLGETRENDERBUFFERPARAMETERIVEXTPROC	glGetRenderbufferParameterivEXT;
extern LIBGLSL_API PFNGLISFRAMEBUFFEREXTPROC				glIsFramebufferEXT;
extern LIBGLSL_API PFNGLBINDFRAMEBUFFEREXTPROC				glBindFramebufferEXT;
extern LIBGLSL_API PFNGLDELETEFRAMEBUFFERSEXTPROC			glDeleteFramebuffersEXT;
extern LIBGLSL_API PFNGLGENFRAMEBUFFERSEXTPROC				glGenFramebuffersEXT;
extern LIBGLSL_API PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC		glCheckFramebufferStatusEXT;
extern LIBGLSL_API PFNGLFRAMEBUFFERTEXTURE1DEXTPROC			glFramebufferTexture1DEXT;
extern LIBGLSL_API PFNGLFRAMEBUFFERTEXTURE2DEXTPROC			glFramebufferTexture2DEXT;
extern LIBGLSL_API PFNGLFRAMEBUFFERTEXTURE3DEXTPROC			glFramebufferTexture3DEXT;
extern LIBGLSL_API PFNGLFRAMEBUFFERRENDERBUFFEREXTPROC		glFramebufferRenderbufferEXT;
extern LIBGLSL_API PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVEXTPROC	glGetFramebufferAttachmentParameterivEXT;
extern LIBGLSL_API PFNGLGENERATEMIPMAPEXTPROC				glGenerateMipmapEXT;

/* OpenGL 1.2 */
extern LIBGLSL_API PFNGLBLENDCOLORPROC glBlendColor;
extern LIBGLSL_API PFNGLBLENDEQUATIONPROC glBlendEquation;
extern LIBGLSL_API PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements;

extern LIBGLSL_API PFNGLTEXIMAGE3DPROC	glTexImage3D;
extern LIBGLSL_API PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D;
extern LIBGLSL_API PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3;

/* OpenGL 1.3 */
extern LIBGLSL_API PFNGLACTIVETEXTUREPROC				glActiveTexture;
extern LIBGLSL_API PFNGLSAMPLECOVERAGEPROC				glSampleCoverage;
extern LIBGLSL_API PFNGLCOMPRESSEDTEXIMAGE3DPROC		glCompressedTexImage3D;
extern LIBGLSL_API PFNGLCOMPRESSEDTEXIMAGE2DPROC		glCompressedTexImage2D;
extern LIBGLSL_API PFNGLCOMPRESSEDTEXIMAGE1DPROC		glCompressedTexImage1D;
extern LIBGLSL_API PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC		glCompressedTexSubImage3D;	
extern LIBGLSL_API PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC		glCompressedTexSubImage2D;
extern LIBGLSL_API PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC		glCompressedTexSubImage1D;
extern LIBGLSL_API PFNGLGETCOMPRESSEDTEXIMAGEPROC		glGetCompressedTexImage;

extern LIBGLSL_API PFNGLCLIENTACTIVETEXTUREPROC glClientActiveTexture;
extern LIBGLSL_API PFNGLMULTITEXCOORD1DPROC glMultiTexCoord1d;
extern LIBGLSL_API PFNGLMULTITEXCOORD1DVPROC glMultiTexCoord1dv;
extern LIBGLSL_API PFNGLMULTITEXCOORD1FPROC glMultiTexCoord1f;
extern LIBGLSL_API PFNGLMULTITEXCOORD1FVPROC glMultiTexCoord1fv;
extern LIBGLSL_API PFNGLMULTITEXCOORD1IPROC glMultiTexCoord1i;
extern LIBGLSL_API PFNGLMULTITEXCOORD1IVPROC glMultiTexCoord1iv;
extern LIBGLSL_API PFNGLMULTITEXCOORD1SPROC glMultiTexCoord1s;
extern LIBGLSL_API PFNGLMULTITEXCOORD1SVPROC glMultiTexCoord1sv;
extern LIBGLSL_API PFNGLMULTITEXCOORD2DPROC glMultiTexCoord2d;
extern LIBGLSL_API PFNGLMULTITEXCOORD2DVPROC glMultiTexCoord2dv;
extern LIBGLSL_API PFNGLMULTITEXCOORD2FPROC glMultiTexCoord2f;
extern LIBGLSL_API PFNGLMULTITEXCOORD2FVPROC glMultiTexCoord2fv;
extern LIBGLSL_API PFNGLMULTITEXCOORD2IPROC glMultiTexCoord2i;
extern LIBGLSL_API PFNGLMULTITEXCOORD2IVPROC glMultiTexCoord2iv;
extern LIBGLSL_API PFNGLMULTITEXCOORD2SPROC glMultiTexCoord2s;
extern LIBGLSL_API PFNGLMULTITEXCOORD2SVPROC glMultiTexCoordsv;
extern LIBGLSL_API PFNGLMULTITEXCOORD3DPROC glMultiTexCoord3d;
extern LIBGLSL_API PFNGLMULTITEXCOORD3DVPROC glMultiTexCoord3dv;
extern LIBGLSL_API PFNGLMULTITEXCOORD3FPROC glMultiTexCoord3f;
extern LIBGLSL_API PFNGLMULTITEXCOORD3FVPROC glMultiTexCoord3fv;
extern LIBGLSL_API PFNGLMULTITEXCOORD3IPROC glMultiTexCoord3i;
extern LIBGLSL_API PFNGLMULTITEXCOORD3IVPROC glMultiTexCoord3iv;
extern LIBGLSL_API PFNGLMULTITEXCOORD3SPROC glMultiTexCoord3s;
extern LIBGLSL_API PFNGLMULTITEXCOORD3SVPROC glMultiTexCoord3sv;
extern LIBGLSL_API PFNGLMULTITEXCOORD4DPROC glMultiTexCoord4d;
extern LIBGLSL_API PFNGLMULTITEXCOORD4DVPROC glMultiTexCoord4dv;
extern LIBGLSL_API PFNGLMULTITEXCOORD4FPROC glMultiTexCoord4f;
extern LIBGLSL_API PFNGLMULTITEXCOORD4FVPROC glMultiTexCoord4fv;
extern LIBGLSL_API PFNGLMULTITEXCOORD4IPROC glMultiTexCoord4i;
extern LIBGLSL_API PFNGLMULTITEXCOORD4IVPROC glMultiTexCoord4iv;
extern LIBGLSL_API PFNGLMULTITEXCOORD4SPROC glMultiTexCoord4s;
extern LIBGLSL_API PFNGLMULTITEXCOORD4SVPROC glMultiTexCoord4sv;

extern LIBGLSL_API PFNGLLOADTRANSPOSEMATRIXFPROC	glLoadTransposeMatrixf;
extern LIBGLSL_API PFNGLLOADTRANSPOSEMATRIXDPROC	glLoadTransposeMatrixd;
extern LIBGLSL_API PFNGLMULTTRANSPOSEMATRIXFPROC	glMultTransposeMatrixf;
extern LIBGLSL_API PFNGLMULTTRANSPOSEMATRIXDPROC	glMultTransposeMatrixd;

/* OpenGL 1.4 */
extern LIBGLSL_API PFNGLBLENDFUNCSEPARATEPROC		glBlendFuncSeparate;
extern LIBGLSL_API PFNGLMULTIDRAWARRAYSPROC			glMultiDrawArrays;
extern LIBGLSL_API PFNGLMULTIDRAWELEMENTSPROC		glMultiDrawElements;

extern LIBGLSL_API PFNGLPOINTPARAMETERFPROC glPointParameterf;
extern LIBGLSL_API PFNGLPOINTPARAMETERFVPROC glPointParameterfv;
extern LIBGLSL_API PFNGLPOINTPARAMETERIPROC glPointParameteri;
extern LIBGLSL_API PFNGLPOINTPARAMETERIVPROC glPointParameteriv;

/* OpenGL 1.5 */
extern LIBGLSL_API PFNGLBINDBUFFERPROC glBindBuffer;
extern LIBGLSL_API PFNGLDELETEBUFFERSPROC glDeleteBuffers;
extern LIBGLSL_API PFNGLGENBUFFERSPROC glGenBuffers;
extern LIBGLSL_API PFNGLISBUFFERPROC glIsBuffer;
extern LIBGLSL_API PFNGLBUFFERDATAPROC glBufferData;
extern LIBGLSL_API PFNGLBUFFERSUBDATAPROC glBufferSubData;
extern LIBGLSL_API PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData;
extern LIBGLSL_API PFNGLMAPBUFFERPROC glMapBuffer;
extern LIBGLSL_API PFNGLUNMAPBUFFERPROC glUnmapBuffer;
extern LIBGLSL_API PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
extern LIBGLSL_API PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv;

/* OpenGL 2.0 */
extern LIBGLSL_API PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
extern LIBGLSL_API PFNGLDRAWBUFFERSPROC glDrawBuffers;
extern LIBGLSL_API PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate;
extern LIBGLSL_API PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate;
extern LIBGLSL_API PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate;

/* GLSL 1.10 */
extern LIBGLSL_API PFNGLATTACHSHADERPROC glAttachShader;
extern LIBGLSL_API PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
extern LIBGLSL_API PFNGLCOMPILESHADERPROC glCompileShader;
extern LIBGLSL_API PFNGLCREATEPROGRAMPROC glCreateProgram;
extern LIBGLSL_API PFNGLCREATESHADERPROC glCreateShader;
extern LIBGLSL_API PFNGLDELETEPROGRAMPROC glDeleteProgram;
extern LIBGLSL_API PFNGLDELETESHADERPROC glDeleteShader;
extern LIBGLSL_API PFNGLDETACHSHADERPROC glDetachShader;
extern LIBGLSL_API PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
extern LIBGLSL_API PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
extern LIBGLSL_API PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib;
extern LIBGLSL_API PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform;
extern LIBGLSL_API PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders;
extern LIBGLSL_API PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
extern LIBGLSL_API PFNGLGETPROGRAMIVPROC glGetProgramiv;
extern LIBGLSL_API PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
extern LIBGLSL_API PFNGLGETSHADERIVPROC glGetShaderiv;
extern LIBGLSL_API PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
extern LIBGLSL_API PFNGLGETSHADERSOURCEPROC glGetShaderSource;
extern LIBGLSL_API PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
extern LIBGLSL_API PFNGLGETUNIFORMFVPROC glGetUniformfv;
extern LIBGLSL_API PFNGLGETUNIFORMIVPROC glGetUniformiv;
extern LIBGLSL_API PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv;
extern LIBGLSL_API PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
extern LIBGLSL_API PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
extern LIBGLSL_API PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv;
extern LIBGLSL_API PFNGLISPROGRAMPROC glIsProgram;
extern LIBGLSL_API PFNGLISSHADERPROC glIsShader;
extern LIBGLSL_API PFNGLLINKPROGRAMPROC glLinkProgram;
extern LIBGLSL_API PFNGLSHADERSOURCEPROC glShaderSource;
extern LIBGLSL_API PFNGLUSEPROGRAMPROC glUseProgram;
extern LIBGLSL_API PFNGLUNIFORM1FPROC glUniform1f;
extern LIBGLSL_API PFNGLUNIFORM2FPROC glUniform2f;
extern LIBGLSL_API PFNGLUNIFORM3FPROC glUniform3f;
extern LIBGLSL_API PFNGLUNIFORM4FPROC glUniform4f;
extern LIBGLSL_API PFNGLUNIFORM1IPROC glUniform1i;
extern LIBGLSL_API PFNGLUNIFORM2IPROC glUniform2i;
extern LIBGLSL_API PFNGLUNIFORM3IPROC glUniform3i;
extern LIBGLSL_API PFNGLUNIFORM4IPROC glUniform4i;
extern LIBGLSL_API PFNGLUNIFORM1FVPROC glUniform1fv;
extern LIBGLSL_API PFNGLUNIFORM2FVPROC glUniform2fv;
extern LIBGLSL_API PFNGLUNIFORM3FVPROC glUniform3fv;
extern LIBGLSL_API PFNGLUNIFORM4FVPROC glUniform4fv;
extern LIBGLSL_API PFNGLUNIFORM1IVPROC glUniform1iv;
extern LIBGLSL_API PFNGLUNIFORM2IVPROC glUniform2iv;
extern LIBGLSL_API PFNGLUNIFORM3IVPROC glUniform3iv;
extern LIBGLSL_API PFNGLUNIFORM4IVPROC glUniform4iv;
extern LIBGLSL_API PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
extern LIBGLSL_API PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
extern LIBGLSL_API PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
extern LIBGLSL_API PFNGLVALIDATEPROGRAMPROC glValidateProgram;
extern LIBGLSL_API PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d;
extern LIBGLSL_API PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv;
extern LIBGLSL_API PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f;
extern LIBGLSL_API PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv;
extern LIBGLSL_API PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s;
extern LIBGLSL_API PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv;
extern LIBGLSL_API PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d;
extern LIBGLSL_API PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv;
extern LIBGLSL_API PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f;
extern LIBGLSL_API PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv;
extern LIBGLSL_API PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s;
extern LIBGLSL_API PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv;
extern LIBGLSL_API PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d;
extern LIBGLSL_API PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv;
extern LIBGLSL_API PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f;
extern LIBGLSL_API PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv;
extern LIBGLSL_API PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s;
extern LIBGLSL_API PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub;
extern LIBGLSL_API PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d;
extern LIBGLSL_API PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f;
extern LIBGLSL_API PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s;
extern LIBGLSL_API PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv;
extern LIBGLSL_API PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv;
extern LIBGLSL_API PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;

/* GLSL ES 1.00 */
extern LIBGLSL_API PFNGLRELEASESHADERCOMPILERPROC  glReleaseShaderCompiler;
extern LIBGLSL_API PFNGLSHADERBINARYPROC glShaderBinary;
extern LIBGLSL_API PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat;
extern LIBGLSL_API PFNGLDEPTHRANGEFPROC glDepthRangef;
extern LIBGLSL_API PFNGLCLEARDEPTHFPROC glClearDepthf;

extern LIBGLSL_API PFNGLISRENDERBUFFERPROC						glIsRenderbuffer;
extern LIBGLSL_API PFNGLBINDRENDERBUFFERPROC					glBindRenderbuffer;
extern LIBGLSL_API PFNGLDELETERENDERBUFFERSPROC					glDeleteRenderbuffers;
extern LIBGLSL_API PFNGLGENRENDERBUFFERSPROC					glGenRenderbuffers;
extern LIBGLSL_API PFNGLRENDERBUFFERSTORAGEPROC					glRenderbufferStorage;
extern LIBGLSL_API PFNGLGETRENDERBUFFERPARAMETERIVPROC			glGetRenderbufferParameteriv;
extern LIBGLSL_API PFNGLISFRAMEBUFFERPROC						glIsFramebuffer;
extern LIBGLSL_API PFNGLBINDFRAMEBUFFERPROC						glBindFramebuffer;
extern LIBGLSL_API PFNGLDELETEFRAMEBUFFERSPROC					glDeleteFramebuffers;
extern LIBGLSL_API PFNGLGENFRAMEBUFFERSPROC						glGenFramebuffers;
extern LIBGLSL_API PFNGLCHECKFRAMEBUFFERSTATUSPROC				glCheckFramebufferStatus;
//extern LIBGLSL_API PFNGLFRAMEBUFFERTEXTURE1DPROC				glFramebufferTexture1D;
extern LIBGLSL_API PFNGLFRAMEBUFFERTEXTURE2DPROC				glFramebufferTexture2D;
//extern LIBGLSL_API PFNGLFRAMEBUFFERTEXTURE3DPROC				glFramebufferTexture3D;
extern LIBGLSL_API PFNGLFRAMEBUFFERRENDERBUFFERPROC				glFramebufferRenderbuffer;
extern LIBGLSL_API PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC	glGetFramebufferAttachmentParameteriv;
extern LIBGLSL_API PFNGLGENERATEMIPMAPPROC						glGenerateMipmap;

#ifndef GL_SHADER_BINARY_FORMATS
#   define GL_SHADER_BINARY_FORMATS     0x8DF8
#endif /* GL_SHADER_BINARY_FORMATS */

/* OES extension functions */

/* GL_OES_mapbuffer */
extern LIBGLSL_API PFNGLMAPBUFFEROESPROC				glMapBufferOES;
extern LIBGLSL_API PFNGLUNMAPBUFFEROESPROC				glUnmapBufferOES;
extern LIBGLSL_API PFNGLGETBUFFERPOINTERVOESPROC		glGetBufferPointervOES;

/* GL_OES_texture_3D */
extern LIBGLSL_API PFNGLTEXIMAGE3DOESPROC				glTexImage3DOES;
extern LIBGLSL_API PFNGLTEXSUBIMAGE3DOESPROC			glTexSubImage3DOES;
extern LIBGLSL_API PFNGLCOPYTEXSUBIMAGE3DOESPROC		glCopyTexSubImage3DOES;
extern LIBGLSL_API PFNGLCOMPRESSEDTEXIMAGE3DOESPROC		glCompressedTexImage3DOES;
extern LIBGLSL_API PFNGLCOMPRESSEDTEXSUBIMAGE3DOESPROC	glCompressedTexSubImage3DOES;
extern LIBGLSL_API PFNGLFRAMEBUFFERTEXTURE3DOES			glFramebufferTexture3DOES;


extern LIBGLSL_API void SetupGLSL(void);
extern LIBGLSL_API int SetupGLSL110(void);
extern LIBGLSL_API int SetupGLSLES100(void);
extern LIBGLSL_API int dmpIsSupported(const char *name);

#ifdef __cplusplus
}
#endif
